import type { PortfolioItem } from '../types/portfolio-item';
import PortfolioHomeImage from '../images/work/portfolio/home.png';
import PortfolioAboutImage from '../images/work/portfolio/about.png';
import PortfolioWorkImage from '../images/work/portfolio/work.png';
import AtmosphereImage from '../images/work/atmosphere/atmosphere.png';
import AtmosphereImageTwo from '../images/work/atmosphere/atmosphere-running.png';
import TodoLightImage from '../images/work/todo/lightmode.png';
import TodoDarkImage from '../images/work/todo/darkmode.png';
import TodoLightCloseupImage from '../images/work/todo/lightmode-closeup.png';
import TodoDarkCloseupImage from '../images/work/todo/darkmode-closeup.png';
import IrishNetworkHomeImage from '../images/work/irish-network/home.png';
import IrishNetworkNewsImage from '../images/work/irish-network/news.png';
import IrishNetworkTeamImage from '../images/work/irish-network/team.png';
import CrwnClothingHomeImage from '../images/work/crwn-clothing/home.png';
import CrwnClothingCartImage from '../images/work/crwn-clothing/cart.png';
import CrwnClothingItemsImage from '../images/work/crwn-clothing/items.png';

const websiteList: PortfolioItem[] = [
  {
    title: 'Portfolio',
    description: [
      'A fun portfolio site aimed at providing an interesting experience for users interested in my work',
      'I had a lot of fun creating this site. As a challenge I wanted to see what I could achieve without using any UI frameworks, and keeping as much of the content powered by HTML and CSS',
      'Built with Typescript, Tailwind CSS, and Astro 🚀',
    ],
    websiteLink: 'https://michaelduren.com/',
    codeLink: 'https://github.com/michael-duren/portfolio',
    images: [PortfolioHomeImage, PortfolioAboutImage, PortfolioWorkImage],
    color: 'bg-rose-100 shadow-rose-900',
  },
  {
    title: 'Atmosphere',
    description: [
      'Atmosphere, A smart partner to help you learn how to make electronic music. Atmosphere gives users the experience of creating melodies and bass lines that are randomly generated by a set of parameters, and the freedom to turn dials and knobs that change the sound. This gives users a unique experience in that many of the roadblocks to understanding basic concepts of electronic music are already taken care of.',
      'The goal of this application is to give users a unique experience both visually and musically. The UI provides real-time feedback on what is happening with the changes the user is making by using an oscilloscope which is a visual representation of sound waves. My own love for electronic music came from experimentation, and Atmosphere gives the user plenty of space to twist sound into unpredictable and exciting experiences.',
      'Built with Typescript, Tailwind, React, Redux, C# .NET, and PostgreSQL',
    ],
    websiteLink: 'https://atmosphere.fly.dev/',
    codeLink: 'https://github.com/michael-duren/atmosphere',
    images: [AtmosphereImage, AtmosphereImageTwo],
    color: 'bg-green-100 shadow-green-900',
  },
  {
    title: 'Irish Network',
    description: [
      'A website and admin panel created for a local non profit Irish Network MN',
      'Features: user profiles and schemas and implement role-based login for users and admins.',
      'Admin panel for board members to edit event details, board member profiles, and images for the event image gallery.',
      'Built with React, Next.js, Typescript, tRPC, Prisma, Tailwind CSS, NextAuth, Supabase, PostgreSQL.',
    ],
    websiteLink: 'https://irish-network-mn.vercel.app/',
    codeLink: 'https://github.com/michael-duren/Irish-Network-MN',
    images: [
      IrishNetworkHomeImage,
      IrishNetworkNewsImage,
      IrishNetworkTeamImage,
    ],
    color: 'bg-blue-100 shadow-blue-900',
  },
  {
    title: 'Todos',
    description: [
      'A simple yet elegant todo app for user to keep track of their tasks. Todos lets you prioritze your busy life with priority, category, and deadline views and settings.',
      "Undo items, view how many you've completed per day. Available in both light and dark mode, ToDos respect your system settings and will automatically switch with your system between light and dark mode.",
      'Built with Typescript, React, TailwindCSS, Node, Express, and PostgreSQL',
    ],
    websiteLink: 'https://todos-michael-d-08c36acec5cc.herokuapp.com/',
    codeLink: 'https://github.com/michael-duren/todos',
    images: [
      TodoLightImage,
      TodoLightCloseupImage,
      TodoDarkImage,
      TodoDarkCloseupImage,
    ],
    color: 'bg-orange-100 shadow-orange-900',
  },
  {
    title: 'Crown Clothing',
    description: ['E-Commerce Application'],
    websiteLink: 'https://endearing-kashata-004ef9.netlify.app/',
    codeLink: 'https://github.com/michael-duren/crwn-clothing',
    images: [
      CrwnClothingHomeImage,
      CrwnClothingCartImage,
      CrwnClothingItemsImage,
    ],
    color: 'bg-violet-100 shadow-violet-900',
  },
];

export default websiteList;
